# # ## vlsp data
# train_data: ../data/VLSP/processed/vlsp_processed_train_SHUFFLE_340_date_06_05_1st_filtered.data
# test_data: ../data/VLSP/processed/vlsp_processed_dev_SHUFFLE_180_date_06_05_1st_filtered.data




# # ## vlsp data
train_data: ../data/VLSP/processed/vlsp_processed_08_05_23_16h_TRAIN_line_442_1st_filtered_with_no_rel_remove_big.data
test_data: ../data/VLSP/processed/vlsp_processed_08_05_23_16h_DEV_line_224_1st_filtered_with_no_rel_remove_big
# embeds: ../embeds/PubMed-VLSP.txt
embeds: 0
folder: ../results/vlsp-test
save_pred: test

# train_data: ../data/VLSP/tunning/vlsp_tunning_train.data
# test_data:  ../data/VLSP/tunning/vlsp_tunning_test.data


# options (chosen from parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
context: true
dist: true
freeze_words: true

# extra
seed: 0
shuffle_data: true
label2ignore: 1:NR:2 # need to label data in VLSP
primary_metric: micro_f
direction: l2r+r2l

# # vlsp data
include_pairs: ['LOCATION-LOCATION', 'LOCATION-PERSON', 'LOCATION-ORGANIZATION', 'PERSON-LOCATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'ORGANIZATION-LOCATION', 'ORGANIZATION-PERSON', 'ORGANIZATION-ORGANIZATION']
classify_pairs: ['PERSON-LOCATION', 'ORGANIZATION-LOCATION', 'LOCATION-LOCATION', 'ORGANIZATION-ORGANIZATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION']


edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
# edges: ['MM', 'ME', 'MS', 'ES', 'SS']
# edges: ['ES', 'SS']
window:

# classify_pairs: [
#     # 1 LOCATED
#     'PERSON-LOCATION, 'ORGANIZATION-LOCATION',
#     # 2 PART–WHOLE
#     'LOCATION-LOCATION, 'ORGANIZATION-ORGANIZATION', #'ORGANIZATION-LOCATION',
#     # 3 PERSONAL–SOCIAL
#     'PERSON-PERSON',
#     # 4 AFFILIATION
#     'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION' #PERSON-LOCATION, 'ORGANIZATION-ORGANIZATION'\]
# ]

# network
batch: 1
epoch: 50
# bilstm_layers: 2
word_dim: 200

type_dim: 10
dist_dim: 10
drop_i: 0.5
drop_m: 0.0
drop_o: 0.3
gc: 10
reg: 0.0001
opt: adam
patience: 10
unk_w_prob: 0.5
min_w_freq: 1

# ------------------------------
batch: 1
bilstm_layers: 1
beta: 0.77
lr: 0.0023
lstm_dim: 100
out_dim: 100
walks_iter: 2