# # ## vlsp data
# train_data: ../data/VLSP/processed/vlsp_processed_train_SHUFFLE_340_date_06_05_1st_filtered.data
# test_data: ../data/VLSP/processed/vlsp_processed_dev_SHUFFLE_180_date_06_05_1st_filtered.data




# # ## vlsp data
# train_data: ../data/VLSP/processed/vlsp_processed_08_05_23_16h_TRAIN_line_442_1st_filtered_with_no_rel_remove_big.data
# test_data: ../data/VLSP/processed/vlsp_processed_08_05_23_16h_DEV_line_224_1st_filtered_with_no_rel_remove_big
embeds: ../embeds/PubMed-VLSP.txt
folder: ../results/vlsp-test
save_pred: test

# train_data: ../data/VLSP/tunning/vlsp_tunning_train.data
# test_data:  ../data/VLSP/tunning/vlsp_tunning_test.data


# options (chosen from parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
context: true
dist: true
freeze_words: true

# extras
seed: 0
shuffle_data: true
label2ignore: 1:NR:2 # need to label data in VLSP
primary_metric: micro_f
# direction: l2r+r2l
direction: l2r+r2l

# # vlsp data
include_pairs: ['LOCATION-LOCATION', 'LOCATION-PERSON', 'LOCATION-ORGANIZATION', 'PERSON-LOCATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'ORGANIZATION-LOCATION', 'ORGANIZATION-PERSON', 'ORGANIZATION-ORGANIZATION']
classify_pairs: ['PERSON-LOCATION', 'ORGANIZATION-LOCATION', 'LOCATION-LOCATION', 'ORGANIZATION-ORGANIZATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION']


edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
# edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind', 'SS']
# edges: ['ES', 'SS', 'SS-ind']
# edges: ['ME', 'ES', 'SS-ind']
# edges: ['ES', 'SS-ind']
window:

# classify_pairs: [
#     # 1 LOCATED
#     'PERSON-LOCATION, 'ORGANIZATION-LOCATION',
#     # 2 PART–WHOLE
#     'LOCATION-LOCATION, 'ORGANIZATION-ORGANIZATION', #'ORGANIZATION-LOCATION',
#     # 3 PERSONAL–SOCIAL
#     'PERSON-PERSON',
#     # 4 AFFILIATION
#     'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION' #PERSON-LOCATION, 'ORGANIZATION-ORGANIZATION'\]
# ]

# network
batch: 1
epoch: 50
# bilstm_layers: 2
word_dim: 192

type_dim: 10
dist_dim: 10
drop_i: 0.55
drop_m: 0.0
drop_o: 0.24
gc: 10
# reg: 0.0001
reg: 0.00011
opt: adam
patience: 10
unk_w_prob: 0.5
min_w_freq: 1

# train_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_402_rm_zero_rel_below_1000_checked_sent_DUPLICATE_3times
# test_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_DEV_line_221_rm_zero_rel_below_1000_checked_sent

# train_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_411_rm_zero_rel_below_3000_checked_sent
# test_data:  ../data/VLSP/processed/vlsp_processed_10_05_23_16h_DEV_line_229_rm_zero_rel_below_3000_checked_sent


# train_data: ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_497_TRAIN
# test_data:  ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_230_DEV


train_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_411_rm_zero_rel_below_3000_checked_sent
test_data:  ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_230_DEV


# train_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_402_rm_zero_rel_below_1000_checked_sent_DUPLICATE_times_code_1_code_2
# train_data: ../data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_402_rm_zero_rel_below_1000_checked_sent

# train_data: ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_497_TRAIN
# test_data:  ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_230_DEV

# train_data: ..data/VLSP/processed/vlsp_processed_10_05_23_16h_TRAIN_line_402_rm_zero_rel_below_1000_checked_sent
# test_data:  ../data/VLSP/processed/vlsp_18_05_23_1h_FOR_BERT_FULL_line_230_DEV

embeds: ../embeds/PubMed-VLSP.txt
freeze_words: true
folder: ../results/vlsp-test
# folder: ../results/vlsp-test-new

# embeds: 0
# freeze_words: false
word_dim: 192

# ------------------------------
batch: 1
bilstm_layers: 1
beta: 0.7
lr: 0.0035
lstm_dim: 80
out_dim: 80
walks_iter: 2