
# # ## vlsp data
train_data: ../data/VLSP/tunning/vlsp_tunning_train.data
test_data:  ../data/VLSP/tunning/vlsp_tunning_test.data
# embeds: ../embeds/PubMed-VLSP.txt
embeds: 0
folder: ../results/vlsp-test
save_pred: test

# network
batch: 2
epoch: 1
bilstm_layers: 1
word_dim: 192
# word_dim: 200
lstm_dim: 20  
out_dim: 20
type_dim: 10
beta: 0.8
dist_dim: 10
drop_i: 0.5
drop_m: 0.0
drop_o: 0.3
lr: 0.0044
gc: 10
reg: 0.0014
opt: adam
patience: 10
unk_w_prob: 0.5
min_w_freq: 1
walks_iter: 1






# options (chosen from parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
context: true
dist: true
freeze_words: true

# extra
seed: 0
shuffle_data: true
label2ignore: 1:NR:2 # need to label data in VLSP
primary_metric: micro_f
direction: l2r+r2l

## origin data
# include_pairs: ['Chemical-Disease', 'Chemical-Chemical', 'Disease-Disease', 'Disease-Chemical']
# classify_pairs: ['Chemical-Disease']

# # vlsp data
include_pairs: ['LOCATION-LOCATION', 'LOCATION-PERSON', 'LOCATION-ORGANIZATION', 'PERSON-LOCATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'ORGANIZATION-LOCATION', 'ORGANIZATION-PERSON', 'ORGANIZATION-ORGANIZATION']
classify_pairs: ['PERSON-LOCATION', 'ORGANIZATION-LOCATION', 'LOCATION-LOCATION', 'ORGANIZATION-ORGANIZATION', 'PERSON-PERSON', 'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION']


edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
# edges: ['MM', 'ME', 'MS', 'ES', 'SS']
# edges: ['ES', 'SS']
window:

# classify_pairs: [
#     # 1 LOCATED
#     'PERSON-LOCATION, 'ORGANIZATION-LOCATION',
#     # 2 PART–WHOLE
#     'LOCATION-LOCATION, 'ORGANIZATION-ORGANIZATION', #'ORGANIZATION-LOCATION',
#     # 3 PERSONAL–SOCIAL
#     'PERSON-PERSON',
#     # 4 AFFILIATION
#     'PERSON-ORGANIZATION', 'LOCATION-ORGANIZATION' #PERSON-LOCATION, 'ORGANIZATION-ORGANIZATION'\]
# ]